name: CrazyAuctionsPlus
author:
- BadBones69
- TRCRedstoner
- Maxlego08
main: studio.trc.bukkit.crazyauctionsplus.Main
version: 1.1.4
api-version: 1.13
description: Plus version of CrazyAuctions plugin, by TRCRedstoner (TRC Studio & PA Project), The original author was BadBones69.
commands: